spring:
  datasource:
    url: jdbc:sqlserver://aditya2305.database.windows.net:1433;database=adityadb;user=aditya@aditya2305;password={password@123};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: aditya
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


